### ISSUE TITLE
Nenhuma categoria foi sincronizada.

### ISSUE THREAD

**Issue by donini** [AnyMarket/magento#39]
Olá instalei o módulo, porém ao realizar as configurações básicas para uso me deparei com a impossibilidade de importar as categorias do meu catálogo para o módulo do AnyMarket, ao tentar importa-las recebo a seguinte msg: Nenhuma categoria foi sincronizada.

O mesmo ocorre ao tentar sincronizar marcas:  Nenhuma marca foi sincronizada.

É um erro comum de configuração, há alguma configuração adicional que devo fazer ou ainda existe um local com faq a respeito do processo de configuração do módulo?

Obrigado!

**Comment by AnyMarket** [comment]
Você pode encontrar todos os dados para a configuração, manutenção e uso do módulo no seguinte endereço: http://developers.anymarket.com.br/tools.html (item "Módulo Magento" no menu a esquerda).

Sobre o não Import de Marcas e Categorias, valide por favor o Token, Host e OI na aba das configurações no menu Acesso. Alem disso valide se o Escopo em que você esta tentando importar-las é o mesmo das configurações.

**Comment by donini** [comment]
Olá pessoal, sigo com o mesmo problema.

Entrei em contato com suporte, validamos as chaves e configurações do módulo, e nada.

Tenho testes da aplicação parados em função deste cenário de erro do anymarket.

Conseguem nos auxiliar?
