### ISSUE TITLE
O script inicial de instalação não está criando tabelas

### ISSUE THREAD

**Issue by ygorlazaro** [AnyMarket/magento#40]
Estou instando o módulo na magento 1.9.2.2 e as tabelas não são criadas por padrão.

Olhei o código do componente e vi que não existem (até onde consegui procurar) rotinas CREATE TABLE.

Eu desativei o componente, não é possível utilizar no momento.

**Comment by alexandreanymarket** [comment]
Boa tarde,
No Magento não é assim que funciona, as tabelas sao criadas usando o Padrao do Magento, ou seja:

$this->getConnection()->createTable($table);


Todas elas estao aqui:
app/code/community/DB1/AnyMarket/sql/db1_anymarket_setup/mysql4-install-1.0.0.php

**Comment by ygorlazaro** [comment]
Entendi.

E esse código ele não seria executado quando se instala o componente, ou eu tenho que chamar ele no terminal?

**Comment by ygorlazaro** [comment]
Porque se ele for chamado durante a instalação, isso não ocorreu no meu caso :( Segui o procedimento de cópia descrita no README, e não use a Magento Connect.

**Comment by ygorlazaro** [comment]
Desculpe, @alexandreanymarket , mas pode me dar uma luz aqui?
